# NOTE: Generated By HttpRunner v3.1.4
# FROM: .\har\mubu_create_doc_fial.har


from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseMubuCreateDocFial(HttpRunner):

    config = Config("testcase description")\
        .verify(False)\
        .base_url("https://mubu.com").variables(**{"host": "mubu.com"})



    teststeps = [
        Step(
            RunRequest("/")
            .get("/")
            .with_headers(
                **{
                    "cache-control": "max-age=0",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://${host}/app",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "_ga": "GA1.2.1653640968.1615893817",
                    "_gid": "GA1.2.1067627155.1616108865",
                    "csrf_token": "446162f6-2f03-48de-8aa5-d96e563b3436",
                    "SESSION": "9c0888c9-c675-4c72-aa88-1564bc245a30",
                    "language": "en-US",
                    "country": "US",
                    "_gat": "1",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1615893817,1615955168,1616020759,1616150561",
                    "SLARDAR_WEB_ID": "d0a3598a-05b3-4825-8ee1-7c9948b61ba2",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1616150580",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/login")
            .get("/login")
            .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "_ga": "GA1.2.1653640968.1615893817",
                    "_gid": "GA1.2.1067627155.1616108865",
                    "csrf_token": "446162f6-2f03-48de-8aa5-d96e563b3436",
                    "SESSION": "9c0888c9-c675-4c72-aa88-1564bc245a30",
                    "language": "en-US",
                    "country": "US",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1615893817,1615955168,1616020759,1616150561",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1616150618",
                    "SLARDAR_WEB_ID": "5a5ccc8a-dc87-4008-9750-0b058d775c12",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/login/password")
            .get("/login/password")
            .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://${host}/login",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "_ga": "GA1.2.1653640968.1615893817",
                    "_gid": "GA1.2.1067627155.1616108865",
                    "csrf_token": "446162f6-2f03-48de-8aa5-d96e563b3436",
                    "SESSION": "9c0888c9-c675-4c72-aa88-1564bc245a30",
                    "language": "en-US",
                    "country": "US",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1615893817,1615955168,1616020759,1616150561",
                    "SLARDAR_WEB_ID": "a09a56a3-8dac-4d12-9f55-71e6f9f05417",
                    "_gat": "1",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1616150688",
                    "reg_prepareId": "1784a167961-1784a167026-4fcf-9bb6-20e6ec9a1bb5",
                    "reg_focusId": "486be1c0-5d02-4fcf-9bb6-1784a168053",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/api/login/submit")
            .post("/api/login/submit")
            .with_headers(
                **{
                    "content-length": "51",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "_ga": "GA1.2.1653640968.1615893817",
                    "_gid": "GA1.2.1067627155.1616108865",
                    "csrf_token": "446162f6-2f03-48de-8aa5-d96e563b3436",
                    "SESSION": "9c0888c9-c675-4c72-aa88-1564bc245a30",
                    "language": "en-US",
                    "country": "US",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1615893817,1615955168,1616020759,1616150561",
                    "_gat": "1",
                    "reg_prepareId": "1784a167961-1784a167026-4fcf-9bb6-20e6ec9a1bb5",
                    "reg_focusId": "486be1c0-5d02-4fcf-9bb6-1784a168053",
                    "SLARDAR_WEB_ID": "cb97c03a-0f8b-4280-8079-ce25cf0cb7a6",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1616150693",
                }
            )
            .with_data(
                {"phone": "18600393078", "password": "20160215ze", "remember": "true"}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/app")
            .get("/app")
            .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://${host}/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "data_unique_id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "_ga": "GA1.2.1653640968.1615893817",
                    "_gid": "GA1.2.1067627155.1616108865",
                    "csrf_token": "446162f6-2f03-48de-8aa5-d96e563b3436",
                    "SESSION": "9c0888c9-c675-4c72-aa88-1564bc245a30",
                    "language": "en-US",
                    "country": "US",
                    "reg_entrance": "https%3A%2F%2F${host}%2F",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1615893817,1615955168,1616020759,1616150561",
                    "_gat": "1",
                    "reg_prepareId": "1784a167961-1784a167026-4fcf-9bb6-20e6ec9a1bb5",
                    "reg_focusId": "486be1c0-5d02-4fcf-9bb6-1784a168053",
                    "SLARDAR_WEB_ID": "cb97c03a-0f8b-4280-8079-ce25cf0cb7a6",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1616150693",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODM1NjkiLCJleHAiOjE2MTg3NDI3MDYsImlhdCI6MTYxNjE1MDcwNn0.QJe5OjxlwiLcH4u7HajHGqS6tmFg2SIQNGaWS5Gkn7IebgKrApYgNc0KEjscUz-Ii53_iTE-f3REKozm8no5wQ",
                    "user_persistence": "3d568093-fd15-400e-82b6-ab5b12ba8dac",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/user/profile")
            .post("https://api2.mubu.com/v3/api/user/profile")
            .with_headers(
                **{
                    "content-length": "0",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODM1NjkiLCJleHAiOjE2MTg3NDI3MDYsImlhdCI6MTYxNjE1MDcwNn0.QJe5OjxlwiLcH4u7HajHGqS6tmFg2SIQNGaWS5Gkn7IebgKrApYgNc0KEjscUz-Ii53_iTE-f3REKozm8no5wQ",
                    "x-request-id": "fb0815fa-e719-4470-b439-d7ab33adb9b5",
                    "version": "3.0.0.21201",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/get_all_documents_page")
            .post("https://api2.mubu.com/v3/api/list/get_all_documents_page")
            .with_headers(
                **{
                    "content-length": "12",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODM1NjkiLCJleHAiOjE2MTg3NDI3MDYsImlhdCI6MTYxNjE1MDcwNn0.QJe5OjxlwiLcH4u7HajHGqS6tmFg2SIQNGaWS5Gkn7IebgKrApYgNc0KEjscUz-Ii53_iTE-f3REKozm8no5wQ",
                    "x-request-id": "2e4c3ca0-0693-450a-bcf0-05587a92a54c",
                    "version": "3.0.0.21201",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"start": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/star_relation/get")
            .get("https://api2.mubu.com/v3/api/list/star_relation/get")
            .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODM1NjkiLCJleHAiOjE2MTg3NDI3MDYsImlhdCI6MTYxNjE1MDcwNn0.QJe5OjxlwiLcH4u7HajHGqS6tmFg2SIQNGaWS5Gkn7IebgKrApYgNc0KEjscUz-Ii53_iTE-f3REKozm8no5wQ",
                    "x-request-id": "1645731a-9286-4e0b-9d88-935843d41787",
                    "version": "3.0.0.21201",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/get_user_params")
            .post("https://api2.mubu.com/v3/api/user/get_user_params")
            .with_headers(
                **{
                    "content-length": "0",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODM1NjkiLCJleHAiOjE2MTg3NDI3MDYsImlhdCI6MTYxNjE1MDcwNn0.QJe5OjxlwiLcH4u7HajHGqS6tmFg2SIQNGaWS5Gkn7IebgKrApYgNc0KEjscUz-Ii53_iTE-f3REKozm8no5wQ",
                    "x-request-id": "9ff88d7a-d79e-481b-a110-1e07144b6787",
                    "version": "3.0.0.21201",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/advertisement/get")
            .post("https://api2.mubu.com/v3/api/advertisement/get")
            .with_headers(
                **{
                    "content-length": "10",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODM1NjkiLCJleHAiOjE2MTg3NDI3MDYsImlhdCI6MTYxNjE1MDcwNn0.QJe5OjxlwiLcH4u7HajHGqS6tmFg2SIQNGaWS5Gkn7IebgKrApYgNc0KEjscUz-Ii53_iTE-f3REKozm8no5wQ",
                    "x-request-id": "50a38dfa-d73d-458d-989c-08bdacf672a1",
                    "version": "3.0.0.21201",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"type": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "30",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODM1NjkiLCJleHAiOjE2MTg3NDI3MDYsImlhdCI6MTYxNjE1MDcwNn0.QJe5OjxlwiLcH4u7HajHGqS6tmFg2SIQNGaWS5Gkn7IebgKrApYgNc0KEjscUz-Ii53_iTE-f3REKozm8no5wQ",
                    "x-request-id": "57905bc6-7b54-4e1e-bc8f-c972bf0c2425",
                    "version": "3.0.0.21201",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/message/get_message_unread")
            .post("https://api2.mubu.com/v3/api/message/get_message_unread")
            .with_headers(
                **{
                    "content-length": "10",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODM1NjkiLCJleHAiOjE2MTg3NDI3MDYsImlhdCI6MTYxNjE1MDcwNn0.QJe5OjxlwiLcH4u7HajHGqS6tmFg2SIQNGaWS5Gkn7IebgKrApYgNc0KEjscUz-Ii53_iTE-f3REKozm8no5wQ",
                    "x-request-id": "780a6cbf-2b98-47ca-8544-0bda41c8bbdb",
                    "version": "3.0.0.21201",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"page": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/create_doc")
            .post("https://api2.mubu.com/v3/api/list/create_doc")
            .with_headers(
                **{
                    "content-length": "25",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODM1NjkiLCJleHAiOjE2MTg3NDI3MDYsImlhdCI6MTYxNjE1MDcwNn0.QJe5OjxlwiLcH4u7HajHGqS6tmFg2SIQNGaWS5Gkn7IebgKrApYgNc0KEjscUz-Ii53_iTE-f3REKozm8no5wQ",
                    "x-request-id": "81038375-cb57-4011-8553-23f53e5712c8",
                    "version": "3.0.0.21201",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": "0", "type": 0})
            .extract()
            .with_jmespath("body.data.id", "docID")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "30",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODM1NjkiLCJleHAiOjE2MTg3NDI3MDYsImlhdCI6MTYxNjE1MDcwNn0.QJe5OjxlwiLcH4u7HajHGqS6tmFg2SIQNGaWS5Gkn7IebgKrApYgNc0KEjscUz-Ii53_iTE-f3REKozm8no5wQ",
                    "x-request-id": "bf349bc5-0e69-4361-b2fb-47ecae3f50fc",
                    "version": "3.0.0.21201",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/current_level")
            .post("https://api2.mubu.com/v3/api/user/current_level")
            .with_headers(
                **{
                    "content-length": "28",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODM1NjkiLCJleHAiOjE2MTg3NDI3MDYsImlhdCI6MTYxNjE1MDcwNn0.QJe5OjxlwiLcH4u7HajHGqS6tmFg2SIQNGaWS5Gkn7IebgKrApYgNc0KEjscUz-Ii53_iTE-f3REKozm8no5wQ",
                    "x-request-id": "e0880e9b-deca-4b18-b9cc-2931c3ca3eac",
                    "version": "3.0.0.21201",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"document_id": "$docID"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/document/edit/get")
            .post("https://api2.mubu.com/v3/api/document/edit/get")
            .with_headers(
                **{
                    "content-length": "36",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODM1NjkiLCJleHAiOjE2MTg3NDI3MDYsImlhdCI6MTYxNjE1MDcwNn0.QJe5OjxlwiLcH4u7HajHGqS6tmFg2SIQNGaWS5Gkn7IebgKrApYgNc0KEjscUz-Ii53_iTE-f3REKozm8no5wQ",
                    "x-request-id": "237b2ac1-bb75-429f-a97e-f74bade16093",
                    "version": "3.0.0.21201",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"docId": "$docID", "password": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/doc/list")
            .post("https://api2.mubu.com/v3/api/refer/doc/list")
            .with_headers(
                **{
                    "content-length": "28",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODM1NjkiLCJleHAiOjE2MTg3NDI3MDYsImlhdCI6MTYxNjE1MDcwNn0.QJe5OjxlwiLcH4u7HajHGqS6tmFg2SIQNGaWS5Gkn7IebgKrApYgNc0KEjscUz-Ii53_iTE-f3REKozm8no5wQ",
                    "x-request-id": "e5d0921d-e39b-4ab5-807d-aaa1a5c5a3d3",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"targetDocId": "$docID"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/register")
            .get("https://api2.mubu.com/v3/api/colla/register")
            .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODM1NjkiLCJleHAiOjE2MTg3NDI3MDYsImlhdCI6MTYxNjE1MDcwNn0.QJe5OjxlwiLcH4u7HajHGqS6tmFg2SIQNGaWS5Gkn7IebgKrApYgNc0KEjscUz-Ii53_iTE-f3REKozm8no5wQ",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "x-request-id": "cebdae06-7752-4fe6-a354-ac0d119ec801",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/node/count")
            .post("https://api2.mubu.com/v3/api/refer/node/count")
            .with_headers(
                **{
                    "content-length": "28",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODM1NjkiLCJleHAiOjE2MTg3NDI3MDYsImlhdCI6MTYxNjE1MDcwNn0.QJe5OjxlwiLcH4u7HajHGqS6tmFg2SIQNGaWS5Gkn7IebgKrApYgNc0KEjscUz-Ii53_iTE-f3REKozm8no5wQ",
                    "x-request-id": "e353337c-5032-4d7f-9863-219187681d60",
                    "version": "3.0.0.21201",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"targetDocId": "$docID"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .get("https://api2.mubu.com/v3/api/colla/members")
            .with_params(**{"memberId": "6709480498422396", "documentId": "$docID"})
            .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODM1NjkiLCJleHAiOjE2MTg3NDI3MDYsImlhdCI6MTYxNjE1MDcwNn0.QJe5OjxlwiLcH4u7HajHGqS6tmFg2SIQNGaWS5Gkn7IebgKrApYgNc0KEjscUz-Ii53_iTE-f3REKozm8no5wQ",
                    "request-id": "members:6709480498422396:1616150713882",
                    "x-request-id": "fc814d27-8312-4a97-8140-1861b1378206",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "456",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "6709480498422396",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODM1NjkiLCJleHAiOjE2MTg3NDI3MDYsImlhdCI6MTYxNjE1MDcwNn0.QJe5OjxlwiLcH4u7HajHGqS6tmFg2SIQNGaWS5Gkn7IebgKrApYgNc0KEjscUz-Ii53_iTE-f3REKozm8no5wQ",
                    "request-id": "MESSAGE:11383569:6709480498422396:3",
                    "x-request-id": "804ddc58-1f7e-4876-abbb-3633d6041563",
                    "version": "3.0.0",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 3,
                    "requestId": "MESSAGE:11383569:6709480498422396:3",
                    "token": "$docID",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "$docID",
                            "version": 0,
                            "content": [
                                {"name": "nameChanged", "title": "k", "original": ""},
                                {"name": "nameChanged", "title": "ka", "original": "k"},
                                {
                                    "name": "nameChanged",
                                    "title": "kai",
                                    "original": "ka",
                                },
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 6.1",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "474",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "6709480498422396",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODM1NjkiLCJleHAiOjE2MTg3NDI3MDYsImlhdCI6MTYxNjE1MDcwNn0.QJe5OjxlwiLcH4u7HajHGqS6tmFg2SIQNGaWS5Gkn7IebgKrApYgNc0KEjscUz-Ii53_iTE-f3REKozm8no5wQ",
                    "request-id": "MESSAGE:11383569:6709480498422396:5",
                    "x-request-id": "abfcb2c6-df25-4901-b6a2-6821da9e97f6",
                    "version": "3.0.0",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 5,
                    "requestId": "MESSAGE:11383569:6709480498422396:5",
                    "token": "$docID",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "$docID",
                            "version": 1,
                            "content": [
                                {
                                    "name": "nameChanged",
                                    "title": "kaik",
                                    "original": "kai",
                                },
                                {
                                    "name": "nameChanged",
                                    "title": "kaika",
                                    "original": "kaik",
                                },
                                {
                                    "name": "nameChanged",
                                    "title": "kaikai",
                                    "original": "kaika",
                                },
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 6.1",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/search_refers")
            .post("https://api2.mubu.com/v3/api/refer/search_refers")
            .with_headers(
                **{
                    "content-length": "53",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODM1NjkiLCJleHAiOjE2MTg3NDI3MDYsImlhdCI6MTYxNjE1MDcwNn0.QJe5OjxlwiLcH4u7HajHGqS6tmFg2SIQNGaWS5Gkn7IebgKrApYgNc0KEjscUz-Ii53_iTE-f3REKozm8no5wQ",
                    "x-request-id": "108be98a-3ce0-4b75-b86f-e445fe91a606",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"docId": "$docID", "keywords": "kaikai", "option": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "364",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "6709480498422396",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODM1NjkiLCJleHAiOjE2MTg3NDI3MDYsImlhdCI6MTYxNjE1MDcwNn0.QJe5OjxlwiLcH4u7HajHGqS6tmFg2SIQNGaWS5Gkn7IebgKrApYgNc0KEjscUz-Ii53_iTE-f3REKozm8no5wQ",
                    "request-id": "MESSAGE:11383569:6709480498422396:7",
                    "x-request-id": "23eb2509-e5c9-463e-8323-d2414a194578",
                    "version": "3.0.0",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 7,
                    "requestId": "MESSAGE:11383569:6709480498422396:7",
                    "token": "$docID",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "$docID",
                            "version": 2,
                            "content": [
                                {
                                    "name": "nameChanged",
                                    "title": "kaikai2",
                                    "original": "kaikai",
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 6.1",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/search_refers")
            .post("https://api2.mubu.com/v3/api/refer/search_refers")
            .with_headers(
                **{
                    "content-length": "54",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODM1NjkiLCJleHAiOjE2MTg3NDI3MDYsImlhdCI6MTYxNjE1MDcwNn0.QJe5OjxlwiLcH4u7HajHGqS6tmFg2SIQNGaWS5Gkn7IebgKrApYgNc0KEjscUz-Ii53_iTE-f3REKozm8no5wQ",
                    "x-request-id": "1adf4a1b-27fc-47f3-8da3-6e63ae7c6c1e",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"docId": "$docID", "keywords": "kaikai2", "option": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "456",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "6709480498422396",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODM1NjkiLCJleHAiOjE2MTg3NDI3MDYsImlhdCI6MTYxNjE1MDcwNn0.QJe5OjxlwiLcH4u7HajHGqS6tmFg2SIQNGaWS5Gkn7IebgKrApYgNc0KEjscUz-Ii53_iTE-f3REKozm8no5wQ",
                    "request-id": "MESSAGE:11383569:6709480498422396:9",
                    "x-request-id": "d3e54c38-46ef-4745-8930-acb0d2e1ca3c",
                    "version": "3.0.0",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 9,
                    "requestId": "MESSAGE:11383569:6709480498422396:9",
                    "token": "$docID",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "$docID",
                            "version": 3,
                            "content": [
                                {
                                    "name": "create",
                                    "created": [
                                        {
                                            "index": 0,
                                            "parentId": None,
                                            "node": {
                                                "id": "J1Tcg7tew6",
                                                "text": "",
                                                "modified": 1616150725337,
                                                "children": [],
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 6.1",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "502",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "6709480498422396",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODM1NjkiLCJleHAiOjE2MTg3NDI3MDYsImlhdCI6MTYxNjE1MDcwNn0.QJe5OjxlwiLcH4u7HajHGqS6tmFg2SIQNGaWS5Gkn7IebgKrApYgNc0KEjscUz-Ii53_iTE-f3REKozm8no5wQ",
                    "request-id": "MESSAGE:11383569:6709480498422396:11",
                    "x-request-id": "770fbd48-bc81-46e4-a846-98110714634e",
                    "version": "3.0.0",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 11,
                    "requestId": "MESSAGE:11383569:6709480498422396:11",
                    "token": "$docID",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "$docID",
                            "version": 4,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "J1Tcg7tew6",
                                                "text": "<span>33</span>",
                                                "modified": 1616150727877,
                                            },
                                            "original": {
                                                "id": "J1Tcg7tew6",
                                                "text": "",
                                                "modified": 1616150725337,
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 6.1",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "518",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "6709480498422396",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODM1NjkiLCJleHAiOjE2MTg3NDI3MDYsImlhdCI6MTYxNjE1MDcwNn0.QJe5OjxlwiLcH4u7HajHGqS6tmFg2SIQNGaWS5Gkn7IebgKrApYgNc0KEjscUz-Ii53_iTE-f3REKozm8no5wQ",
                    "request-id": "MESSAGE:11383569:6709480498422396:13",
                    "x-request-id": "93739f55-e272-481a-987f-2a62973645b0",
                    "version": "3.0.0",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 13,
                    "requestId": "MESSAGE:11383569:6709480498422396:13",
                    "token": "$docID",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "$docID",
                            "version": 5,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "J1Tcg7tew6",
                                                "text": "<span>333</span>",
                                                "modified": 1616150728398,
                                            },
                                            "original": {
                                                "id": "J1Tcg7tew6",
                                                "text": "<span>33</span>",
                                                "modified": 1616150727877,
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 6.1",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "458",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "6709480498422396",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODM1NjkiLCJleHAiOjE2MTg3NDI3MDYsImlhdCI6MTYxNjE1MDcwNn0.QJe5OjxlwiLcH4u7HajHGqS6tmFg2SIQNGaWS5Gkn7IebgKrApYgNc0KEjscUz-Ii53_iTE-f3REKozm8no5wQ",
                    "request-id": "MESSAGE:11383569:6709480498422396:15",
                    "x-request-id": "de1f2709-fc51-4fcb-af1b-8f126ccddbad",
                    "version": "3.0.0",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 15,
                    "requestId": "MESSAGE:11383569:6709480498422396:15",
                    "token": "$docID",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "$docID",
                            "version": 6,
                            "content": [
                                {
                                    "name": "create",
                                    "created": [
                                        {
                                            "index": 1,
                                            "parentId": None,
                                            "node": {
                                                "id": "YmrSfP5PmU",
                                                "text": "",
                                                "modified": 1616150728793,
                                                "children": [],
                                            },
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 6.1",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "502",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "6709480498422396",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODM1NjkiLCJleHAiOjE2MTg3NDI3MDYsImlhdCI6MTYxNjE1MDcwNn0.QJe5OjxlwiLcH4u7HajHGqS6tmFg2SIQNGaWS5Gkn7IebgKrApYgNc0KEjscUz-Ii53_iTE-f3REKozm8no5wQ",
                    "request-id": "MESSAGE:11383569:6709480498422396:16",
                    "x-request-id": "cde3161d-927b-4190-a252-ba8e2d54b45c",
                    "version": "3.0.0",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 16,
                    "requestId": "MESSAGE:11383569:6709480498422396:16",
                    "token": "$docID",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "$docID",
                            "version": 7,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "YmrSfP5PmU",
                                                "text": "<span>89</span>",
                                                "modified": 1616150730348,
                                            },
                                            "original": {
                                                "id": "YmrSfP5PmU",
                                                "text": "",
                                                "modified": 1616150728793,
                                            },
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 6.1",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "518",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "6709480498422396",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODM1NjkiLCJleHAiOjE2MTg3NDI3MDYsImlhdCI6MTYxNjE1MDcwNn0.QJe5OjxlwiLcH4u7HajHGqS6tmFg2SIQNGaWS5Gkn7IebgKrApYgNc0KEjscUz-Ii53_iTE-f3REKozm8no5wQ",
                    "request-id": "MESSAGE:11383569:6709480498422396:18",
                    "x-request-id": "45e83110-154b-4e99-8cf9-ce7a64087afa",
                    "version": "3.0.0",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 18,
                    "requestId": "MESSAGE:11383569:6709480498422396:18",
                    "token": "$docID",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "$docID",
                            "version": 8,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "YmrSfP5PmU",
                                                "text": "<span>890</span>",
                                                "modified": 1616150730622,
                                            },
                                            "original": {
                                                "id": "YmrSfP5PmU",
                                                "text": "<span>89</span>",
                                                "modified": 1616150730348,
                                            },
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 6.1",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "521",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "6709480498422396",
                    "user-agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "9da7a560-7026-46c3-be14-e257d1719b30",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODM1NjkiLCJleHAiOjE2MTg3NDI3MDYsImlhdCI6MTYxNjE1MDcwNn0.QJe5OjxlwiLcH4u7HajHGqS6tmFg2SIQNGaWS5Gkn7IebgKrApYgNc0KEjscUz-Ii53_iTE-f3REKozm8no5wQ",
                    "request-id": "MESSAGE:11383569:6709480498422396:20",
                    "x-request-id": "822763f8-5d21-4c13-affc-da582d640cf2",
                    "version": "3.0.0",
                    "origin": "https://${host}",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://${host}/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 20,
                    "requestId": "MESSAGE:11383569:6709480498422396:20",
                    "token": "$docID",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "$docID",
                            "version": 9,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "YmrSfP5PmU",
                                                "text": "<span>890ze</span>",
                                                "modified": 1616150732982,
                                            },
                                            "original": {
                                                "id": "YmrSfP5PmU",
                                                "text": "<span>890</span>",
                                                "modified": 1616150730622,
                                            },
                                            "path": ["nodes", 1],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "Windows",
                        "osVersion": "NT 6.1",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseMubuCreateDocFial().test_start()
